# Generated by Django 5.0.6 on 2026-08-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('consultant', 'Consultant'), ('company', 'Entreprise'), ('auditor', 'Auditeur'), ('org_user', 'Utilisateur organisation')], default='consultant', max_length=16),
        ),
    ]
