# Generated by Django 5.0.6 on 2026-08-12 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=48, unique=True)),
                ('label_fr', models.CharField(max_length=128)),
                ('label_ar', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalDataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=48, unique=True)),
                ('label_fr', models.CharField(max_length=128)),
                ('label_ar', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=48, unique=True)),
                ('label_fr', models.CharField(max_length=128)),
                ('label_ar', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('service', models.CharField(blank=True, max_length=255, verbose_name='Nature du service')),
                ('has_contract', models.BooleanField(default=False)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processors', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('purpose', models.TextField(blank=True, verbose_name='Finalité')),
                ('department', models.CharField(blank=True, max_length=128, verbose_name='Service responsable')),
                ('owner_name', models.CharField(blank=True, max_length=128, verbose_name='Responsable')),
                ('status', models.CharField(choices=[('propose', 'Proposé'), ('brouillon', 'Brouillon'), ('renseigne', 'Renseigné'), ('a_verifier', 'À vérifier'), ('verifie', 'Vérifié'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=16)),
                ('data_sources', models.CharField(blank=True, max_length=255, verbose_name='Origine des données')),
                ('storage_type', models.CharField(blank=True, choices=[('papier', 'Papier'), ('informatique', 'Informatique'), ('mixte', 'Mixte')], max_length=16)),
                ('retention_duration', models.CharField(blank=True, max_length=128)),
                ('retention_location', models.CharField(blank=True, max_length=255)),
                ('recipients', models.TextField(blank=True, verbose_name='Destinataires')),
                ('interconnection', models.BooleanField(default=False)),
                ('interconnection_details', models.TextField(blank=True)),
                ('transfer_abroad', models.BooleanField(default=False)),
                ('transfer_country', models.CharField(blank=True, max_length=128)),
                ('transfer_recipient', models.CharField(blank=True, max_length=255)),
                ('transfer_details', models.TextField(blank=True)),
                ('consent_required', models.BooleanField(default=False)),
                ('consent_method', models.CharField(blank=True, max_length=255)),
                ('consent_proof', models.CharField(blank=True, max_length=255)),
                ('rights_information', models.TextField(blank=True, verbose_name='Information & droits des personnes')),
                ('created_from', models.CharField(default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processings', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('data_categories', models.ManyToManyField(blank=True, to='processing.personaldatacategory')),
                ('subject_categories', models.ManyToManyField(blank=True, to='processing.datasubjectcategory')),
                ('processors', models.ManyToManyField(blank=True, to='processing.processor')),
                ('security_measures', models.ManyToManyField(blank=True, to='processing.securitymeasure')),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
    ]
