# Generated by Django 5.0.6 on 2026-08-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.PositiveIntegerField(unique=True)),
                ('domain_fr', models.CharField(max_length=255)),
                ('domain_ar', models.CharField(blank=True, max_length=255)),
                ('name_fr', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('purpose_fr', models.TextField(blank=True)),
                ('purpose_ar', models.TextField(blank=True)),
                ('category_fr', models.TextField(blank=True)),
                ('category_ar', models.TextField(blank=True)),
                ('subject_categories_fr', models.TextField(blank=True)),
                ('subject_categories_ar', models.TextField(blank=True)),
                ('data_categories_fr', models.TextField(blank=True)),
                ('data_categories_ar', models.TextField(blank=True)),
                ('retention_fr', models.CharField(blank=True, max_length=255)),
                ('retention_ar', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['domain_fr', 'name_fr'],
            },
        ),
    ]
