# Generated by Django 5.0.6 on 2026-08-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_processingtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingactivity',
            name='version_major',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='version_minor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
