# Generated by Django 5.0.6 on 2026-08-15 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_processingactivity_version_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingactivity',
            name='consent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='consent_evidence',
            field=models.FileField(blank=True, null=True, upload_to='consent_evidence/%Y/%m/', verbose_name='Preuve du consentement'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='consent_evidence_retention',
            field=models.CharField(blank=True, max_length=128, verbose_name='Conservation de la preuve'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='consent_support',
            field=models.CharField(blank=True, max_length=128, verbose_name='Support'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='consent_withdrawal',
            field=models.TextField(blank=True, verbose_name='Possibilité de retrait'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='recipient_category',
            field=models.CharField(blank=True, max_length=128, verbose_name='Catégorie de destinataire'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='recipient_frequency',
            field=models.CharField(blank=True, max_length=128, verbose_name='Fréquence'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='recipient_has_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='recipient_mode',
            field=models.CharField(blank=True, max_length=128, verbose_name='Mode de communication'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='recipient_purpose',
            field=models.TextField(blank=True, verbose_name='Finalité de la communication'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='recipient_security_measures',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='transfer_data_types',
            field=models.TextField(blank=True, verbose_name='Types de données transférées'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='transfer_evidence',
            field=models.FileField(blank=True, null=True, upload_to='transfer_evidence/%Y/%m/', verbose_name='Document justificatif'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='transfer_guarantees',
            field=models.TextField(blank=True, verbose_name='Garanties existantes'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='transfer_hosting',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hébergement'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='transfer_mode',
            field=models.CharField(blank=True, max_length=128, verbose_name='Mode de transfert'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='transfer_provider',
            field=models.CharField(blank=True, max_length=255, verbose_name='Prestataire'),
        ),
        migrations.AddField(
            model_name='processor',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='processor_contracts/%Y/%m/', verbose_name='Contrat'),
        ),
        migrations.AddField(
            model_name='processor',
            name='data_access',
            field=models.ManyToManyField(blank=True, to='processing.personaldatacategory', verbose_name='Données auxquelles il a accès'),
        ),
        migrations.CreateModel(
            name='ProcessingDataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_label', models.CharField(blank=True, max_length=128, verbose_name='Donnée (libre)')),
                ('is_sensitive', models.BooleanField(default=False, verbose_name='Caractère sensible')),
                ('source', models.CharField(blank=True, max_length=255)),
                ('purpose', models.TextField(blank=True, verbose_name='Finalité')),
                ('retention', models.CharField(blank=True, max_length=128, verbose_name='Durée de conservation')),
                ('recipient', models.CharField(blank=True, max_length=255, verbose_name='Destinataire')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='processing.personaldatacategory')),
                ('processing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_items', to='processing.processingactivity')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
