# Generated by Django 5.0.6 on 2026-08-15 16:15

import mrafiq.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_processingactivity_consent_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingdataitem',
            name='custom_label',
            field=mrafiq.fields.EncryptedTextField(blank=True, verbose_name='Donnée (libre)'),
        ),
        migrations.AlterField(
            model_name='processingdataitem',
            name='purpose',
            field=mrafiq.fields.EncryptedTextField(blank=True, verbose_name='Finalité'),
        ),
        migrations.AlterField(
            model_name='processingdataitem',
            name='recipient',
            field=mrafiq.fields.EncryptedTextField(blank=True, verbose_name='Destinataire'),
        ),
        migrations.AlterField(
            model_name='processingdataitem',
            name='source',
            field=mrafiq.fields.EncryptedTextField(blank=True),
        ),
    ]
