# Generated by Django 5.0.6 on 2026-08-14 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('title_fr', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('charte', 'Charte'), ('engagement', 'Engagement'), ('note', "Note d'information"), ('politique', 'Politique'), ('contrat', 'Contrat'), ('decision', 'Décision')], max_length=16)),
                ('source_file', models.FileField(upload_to='document_templates/')),
                ('mergeable', models.BooleanField(default=False, help_text="Le nom de l'entreprise peut être injecté automatiquement dans ce modèle.")),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='generated_documents/%Y/%m/')),
                ('status', models.CharField(choices=[('genere', 'Généré'), ('valide', 'Validé')], default='genere', max_length=16)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='companies.company')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documenttemplate')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
