# Generated by Django 5.0.6 on 2026-08-14 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Service / Département')),
                ('manager_name', models.CharField(blank=True, max_length=128, verbose_name='Nom et prénom du responsable')),
                ('manager_phone', models.CharField(blank=True, max_length=32, verbose_name='Téléphone du responsable')),
                ('manager_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du responsable')),
                ('order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='companies.company')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
