# Generated by Django 5.0.6 on 2026-08-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='controller_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='controller_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nom et prénom'),
        ),
        migrations.AddField(
            model_name='company',
            name='controller_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='company',
            name='controller_qualite',
            field=models.CharField(blank=True, max_length=128, verbose_name='Qualité'),
        ),
        migrations.AddField(
            model_name='company',
            name='dpo_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='dpo_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nom et prénom'),
        ),
        migrations.AddField(
            model_name='company',
            name='dpo_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='company',
            name='dpo_specialite',
            field=models.CharField(blank=True, max_length=255, verbose_name='Diplôme ou spécialité'),
        ),
    ]
