# Generated by Django 5.0.6 on 2026-08-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_controller_email_company_controller_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='commune',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='company',
            name='dpo_status',
            field=models.CharField(choices=[('aucun', 'Sans DPO'), ('en_cours', 'En cours de désignation'), ('designe', 'Désigné')], default='aucun', max_length=16),
        ),
        migrations.AddField(
            model_name='company',
            name='internal_organisation',
            field=models.TextField(blank=True, verbose_name='Organisation interne'),
        ),
        migrations.AddField(
            model_name='company',
            name='nis',
            field=models.CharField(blank=True, max_length=64, verbose_name='NIS'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site internet'),
        ),
    ]
