# Generated by Django 5.0.6 on 2026-08-15 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_commune_company_dpo_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droit', models.CharField(choices=[('information', "Droit à l'information"), ('acces', "Droit d'accès"), ('rectification', 'Droit de rectification'), ('opposition', "Droit d'opposition")], max_length=16)),
                ('mecanisme_existe', models.BooleanField(blank=True, null=True)),
                ('procedure', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, max_length=128)),
                ('delai_interne', models.CharField(blank=True, max_length=64)),
                ('formulaire_existe', models.BooleanField(default=False)),
                ('preuve', models.FileField(blank=True, null=True, upload_to='rights_evidence/%Y/%m/')),
                ('niveau', models.CharField(choices=[('a_verifier', 'À vérifier'), ('conforme', 'Conforme'), ('partiel', 'Partiel'), ('non_conforme', 'Non conforme')], default='a_verifier', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights_procedures', to='companies.company')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['droit'],
                'unique_together': {('company', 'droit')},
            },
        ),
        migrations.CreateModel(
            name='SecurityChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('acces', "Contrôle d'accès"), ('authentification', 'Authentification'), ('mots_de_passe', 'Mots de passe'), ('sauvegardes', 'Sauvegardes'), ('antivirus', 'Antivirus'), ('parefeu', 'Pare-feu'), ('chiffrement', 'Chiffrement'), ('journalisation', 'Journalisation'), ('habilitations', 'Contrôle des habilitations'), ('physique', 'Sécurité physique'), ('incidents', 'Gestion des incidents'), ('confidentialite', 'Confidentialité'), ('sensibilisation', 'Sensibilisation du personnel'), ('charte', 'Charte de sécurité')], max_length=24)),
                ('in_place', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='security_evidence/%Y/%m/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_checklist', to='companies.company')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item'],
                'unique_together': {('company', 'item')},
            },
        ),
    ]
