# Generated by Django 5.0.6 on 2026-08-15 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_rightsprocedure_securitychecklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name_fr', models.CharField(max_length=64)),
                ('name_ar', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='wilaya',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='companysite',
            name='wilaya',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name_fr', models.CharField(max_length=128)),
                ('name_ar', models.CharField(max_length=128)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='companies.wilaya')),
            ],
            options={
                'ordering': ['wilaya_id', 'name_fr'],
                'unique_together': {('wilaya', 'code')},
            },
        ),
    ]
