# Generated by Django 5.0.6 on 2026-08-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='anpdp_created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Date de création du compte'),
        ),
        migrations.AddField(
            model_name='company',
            name='anpdp_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='Mot de passe'),
        ),
        migrations.AddField(
            model_name='company',
            name='anpdp_username',
            field=models.CharField(blank=True, max_length=128, verbose_name="Nom d'utilisateur"),
        ),
    ]
