# Generated by Django 5.0.6 on 2026-08-18 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_anpdp_created_at_company_anpdp_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnpdpDossierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('formulaire', 'Formulaire signé'), ('rdv', 'Fiche de réservation du rendez-vous'), ('contrat_sous_traitant', 'Contrat conclu avec le sous-traitant'), ('contrat_destinataire', 'Contrat conclu avec le destinataire (transfert à l’étranger)'), ('statuts', "Statuts de l'organisme"), ('delegation_signature', 'Délégation de signature'), ('registre_commerce', 'Registre de commerce'), ('autorisation_activite', "Autorisation d'exercice de l'activité")], max_length=32)),
                ('available', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='anpdp_dossier/%Y/%m/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anpdp_dossier_items', to='companies.company')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item'],
                'unique_together': {('company', 'item')},
            },
        ),
    ]
