# Generated by Django 5.0.6 on 2026-08-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_anpdpdossieritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dpo_poste',
            field=models.CharField(blank=True, max_length=128, verbose_name='Poste occupé'),
        ),
    ]
