# Generated by Django 5.0.6 on 2026-08-13 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='diagnostic_evidence/%Y/%m/', verbose_name='Pièce justificative'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='processing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostics', to='processing.processingactivity'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Responsable interrogé'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='respondent_role',
            field=models.CharField(blank=True, max_length=128, verbose_name='Fonction'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='service',
            field=models.CharField(blank=True, max_length=128, verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='question',
            name='rationale_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='rationale_fr',
            field=models.TextField(blank=True, verbose_name='Pourquoi cette question ?'),
        ),
    ]
