# Generated by Django 5.0.6 on 2026-08-15 16:15

import mrafiq.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0002_answer_evidence_diagnostic_processing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=mrafiq.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=mrafiq.fields.EncryptedTextField(blank=True),
        ),
    ]
